### ISSUE TITLE
The modularization plan TODO list, don't open

### ISSUE THREAD

**Issue by quat1024** [quat1024/incorporeal#27]
I have not pushed this stuff because it *mega* breaks the build and I don't like doing that, and silly me forgot to make a branch, and I just don't like pushing heavily unfinished stuff anyways. Just a personal todo

- [ ] Make sure the API is safe against features being disabled and responds in a useful way
- [x] Remove these classes and move their entries into dedicated feature classes:
  - [x] IncorporeticBlocks
  - [x] IncorporeticEntities
  - [x] IncorporeticFluffBlocks/Items (merge into decorative blocks)
  - [x] IncorporeticTiles
  - [x] OldItemsClass
- [x] Event handlers:
  - [x] pull them apart into dedicated module classes, if it makes sense (only 1 module using the event)
  - [x] leave them in core/event if not
  - [x] conditionally subscribe them based on the enabled features
- [ ] Some miscellaneous junk I need to rehome:
  - [x] IncorporeticFlowers (i think this can safely go in Corporetics)
  - [x] IncorporeticLexicon (will need redoing with the module system)
  - [ ] The packet handler maybe?
  - [x] Whatever depends on enumdyecolordataserializer
- [x] Sort out the big pile of etc classes, a lot of cygnus stuff snuck in there
- [ ] ***TEST*** it
  - [ ] Data serializer shenanigans could happen again, watch out for that (make sure feature order is deterministic, I guess)
  - [ ] All sorts of enabled/disabled combinations
- [x] Source code pass to make sure no weird fully qualified names snuck in there
